name: ecommerce-backend

on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
        working-directory: /home/runner/work/eccommerce-backend/eccommerce-backend/package.json
      - name: Run tests
        run: yarn test
        working-directory: /home/runner/work/eccommerce-backend/eccommerce-backend/package.json
