name: ecommerce-backend

on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: yarn install
        working-directory: ./
      - name: Run tests
        run: yarn test
        working-directory: ./
